# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0

name: Namespace Guard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-this-repo:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Namespace Guard
        shell: pwsh
        run: pwsh -File "./tools/Test-Namespace.ps1" -RepoRoot (Resolve-Path ".").Path
