# SPDX-License-Identifier: Apache-2.0
name: SBX Smoke (Ingress health)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check /http/health
        run: |
          code=$(curl -fsSL -o /dev/null -w "%{http_code}" https://sbx.gobee.io/http/health)
          echo "HTTP: $code"
          test "$code" = "200"
      - name: Check /ws/health
        run: |
          code=$(curl -fsSL -o /dev/null -w "%{http_code}" https://sbx.gobee.io/ws/health)
          echo "WS: $code"
          test "$code" = "200"
